### ISSUE TITLE
所有命令 貌似都无法使用

### ISSUE THREAD

**Issue by wangchuanlai** [lich4/TrollStoreRemoteHelper#1]
iphone11  16.3

**Comment by lich4** [comment]
问题描述清楚，否则无法帮你解决。
安装新版前要卸载旧的，否则旧版服务无法自动关闭，新版不生效

**Comment by wangchuanlai** [comment]
从未安装过旧版本 初始版本就是1.3
问题
ssh 中 执行 ls 命令 
(漫长的等待 ， 无任何反馈) 
尝试 强行断开ssh 连接 
在次 连接 ssh 已经无法连接
UI中 无法强行重启 ssh 服务 建议增加 设置选项

**Comment by wangchuanlai** [comment]
> 问题描述清楚，否则无法帮你解决。 安装新版前要卸载旧的，否则旧版服务无法自动关闭，新版不生效

从未安装过旧版本 初始版本就是1.3
问题
ssh 中 执行 ls 命令
(漫长的等待 ， 无任何反馈)
尝试 强行断开ssh 连接
在次 连接 ssh 已经无法连接
UI中 无法强行重启 ssh 服务 建议增加 设置选项

**Comment by wangchuanlai** [comment]
> 问题描述清楚，否则无法帮你解决。 安装新版前要卸载旧的，否则旧版服务无法自动关闭，新版不生效
![B437D701-83BB-4734-B210-FF18C91578F9](https://github.com/lich4/TrollStoreRemoteHelper/assets/28477135/ba6c147b-3977-4ba4-a489-32aa11a359f1)

**Comment by lich4** [comment]
你是不是提问错地方了？你的ssh不能用与我这个chargelimiter软件有啥关系

**Comment by lich4** [comment]
哦，这个哈，因为arm64e(即XR以上型号)不支持fork函数，而一般的sshd和shell都用fork实现。 sshd我用了一个 posix_spawn版本的，所以sshd可以用，shell没找到posix_spawn版本的，都是fork方式的，所以shell无法正常执行，只能使用一些内置命令比如echo。此外可以通过ssh的方式执行命令，ssh root@??? "ls -al"这种
arm64则无此问题

**Comment by lich4** [comment]
如果有人开发一个posix_spawn版的shell我就能整合进去，这个工作量太大了没时间搞

**Comment by lich4** [comment]
已解决，最终用gemini搞定
