### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by xiaosan-re** [lich4/TrollStoreRemoteHelper#2]
错误提示：
TrollStoreRemoteHelper/TrollStoreRemoteHelper/utils.mm:62:13 'posix_spawn_file_actions_addchdir_np' is unavailable: not available on iOS

环境信息：
Xcode: Version 14.3.1 
mac os: 13.6.7

谢谢！

**Comment by lich4** [comment]
把对应系统头文件里的相关的unavailble宏去掉即可. 这是限制你在iOS上编译用的. 越狱/巨魔开发为非常规开发, 所以直接去除即可
如果有洁癖, 不想这么做, 也可以自己造一个spawn.h, 麻烦一些

**Comment by xiaosan-re** [comment]
> 把对应系统头文件里的相关的unavailble宏去掉即可. 这是限制你在iOS上编译用的. 越狱/巨魔开发为非常规开发, 所以直接去除即可 如果有洁癖, 不想这么做, 也可以自己造一个spawn.h, 麻烦一些

非常感谢，成功了。
